Repository truecharts/containers, pull requests merged in 2022-08, with the labels that each got.

#5021 fix(images): update atlassian/jira-servicedesk digest to dd7c89a
  mirror/jira-service-desk/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5020 fix(images): update adminer digest to a2ffb89
  mirror/adminer/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5024 fix(images): update b3log/siyuan digest to 928bf50
  mirror/siyuan/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5023 fix(images): update avpnusr/torprivoxy digest to 6b29f4b
  mirror/torprivoxy/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5022 fix(images): update atlassian/jira-software digest to 51e75d6
  mirror/jira-software/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5027 fix(images): update bitnami/dokuwiki digest to 561fd27
  mirror/dokuwiki/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5028 fix(images): update bitnami/mariadb digest to ecb74b8
  mirror/mariadb/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5025 fix(images): update binhex/arch-rider digest to 2896d48
  mirror/rider/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5026 fix(images): update bitnami/alertmanager digest to ab793eb
  mirror/alertmanager/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5029 fix(images): update directus/directus digest to 00df340
  mirror/directus/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5030 fix(images): update diygod/rsshub digest to 14fa501
  mirror/rsshub/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5031 fix(images): update docker digest to f8c65c9
  mirror/docker-in-docker/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5034 fix(images): update drakkan/sftpgo digest to ad44239
  mirror/sftpgo/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5036 fix(images): update eafxx/traktarr digest to 6ba2b75
  mirror/traktarr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5035 fix(images): update dtjs48jkt/twonkyserver digest to 5276a1f
  mirror/twonky-server/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5033 fix(images): update docker.io/odoo digest to 78363e0
  mirror/odoo/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5038 fix(images): update friendica digest to 35ac104
  mirror/friendica/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5037 fix(images): update factoriotools/factorio digest to a06817c
  mirror/factorio/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5042 fix(images): update ghcr.io/linuxserver/digikam digest to fa77e0c
  mirror/digikam/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5039 fix(images): update ghcr.io/linuxserver/budge digest to f8a02c0
  mirror/budge/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5043 fix(images): update ghcr.io/linuxserver/duckdns digest to 8f4ab3b
  mirror/duckdns/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5032 fix(images): update docker.io/nextcloud digest to eaca1e9
  mirror/nextcloud-fpm/Dockerfile
  mirror/nextcloud/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5040 fix(images): update ghcr.io/linuxserver/darktable digest to 81cf351
  mirror/darktable/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5046 fix(images): update ghcr.io/linuxserver/fleet digest to ebb9e84
  mirror/fleet/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5041 fix(images): update ghcr.io/linuxserver/ddclient digest to aeab2ee
  mirror/ddclient/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5044 fix(images): update ghcr.io/linuxserver/emulatorjs digest to 506e8d4
  mirror/emulatorjs/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5045 fix(images): update ghcr.io/linuxserver/filezilla digest to c36f940
  mirror/filezilla/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5048 fix(images): update ghcr.io/linuxserver/grocy digest to a43166c
  mirror/grocy/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5050 fix(images): update ghcr.io/linuxserver/synclounge digest to 895bfc8
  mirror/synclounge/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5049 fix(images): update ghcr.io/linuxserver/smokeping digest to f0161c9
  mirror/smokeping/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5051 fix(images): update ghcr.io/linuxserver/ubooquity digest to f1f8134
  mirror/ubooquity/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5052 fix(images): update tombursch/kitchenowl-web digest to 908c229
  mirror/kitchenowl-web/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5047 fix(images): update ghcr.io/linuxserver/freshrss digest to 509c7bf
  mirror/freshrss/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5017 feat(images): update koenkk/zigbee2mqtt to 1.27.0
  mirror/zigbee2mqtt/Dockerfile
Labels: automerge

#5015 feat(images): update inventree/inventree to 0.8.0
  mirror/inventree/Dockerfile
Labels: automerge

#5014 feat(images): update ghcr.io/autobrr/autobrr to v1.3.0
  mirror/autobrr/Dockerfile
Labels: automerge

#5013 fix(images): update vabene1111/recipes to 1.3.3
  mirror/recipes/Dockerfile
Labels: automerge

#5012 fix(images): update ghcr.io/flaresolverr/flaresolverr to v2.2.6
  mirror/flaresolverr/Dockerfile
Labels: automerge

#5011 fix(images): update docker.io/jellyfin/jellyfin to 10.8.3
  mirror/jellyfin/Dockerfile
Labels: automerge

#5010 fix(images): update xavierh/goaccess-for-nginxproxymanager digest to a25583b
  mirror/goaccess-npm-logs/Dockerfile
Labels: automerge

#5009 fix(images): update webpsh/webps digest to 8dcb299
  mirror/webp-server/Dockerfile
Labels: automerge

#5007 feat(mymediaforalexa): Add mymediaforalexa
  mirror/mymediaforalexa/Dockerfile
  mirror/mymediaforalexa/PLATFORM
Labels: automerge

#5006 feat(rickroll): Add rickroll images
  mirror/rickroll-fhd-game/Dockerfile
  mirror/rickroll-fhd-game/PLATFORM
  mirror/rickroll-fhd-onclick/Dockerfile
  mirror/rickroll-fhd-onclick/PLATFORM
  mirror/rickroll-fhd/Dockerfile
  mirror/rickroll-fhd/PLATFORM
  mirror/rickroll-onclick/Dockerfile
  mirror/rickroll-onclick/PLATFORM
Labels: automerge

#5016 feat(images): update kimai/kimai2 to apache-1.22.1-prod
  mirror/kimai/Dockerfile
Labels: automerge

#5055 fix(images): update bitnami/mongodb digest to 6f7f2a3
  mirror/mongodb/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5056 fix(images): update bitnami/phpbb digest to d5a61cf
  mirror/phpbb/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5053 fix(images): update bitnami/matomo digest to 64029c0
  mirror/matomo/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5058 fix(images): update bitnami/prometheus digest to 6262bb9
  mirror/prometheus/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5054 fix(images): update bitnami/memcached digest to eeafc93
  mirror/memcached/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5060 fix(images): update bitnami/redis digest to 1c04a01
  mirror/redis/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5057 fix(images): update bitnami/postgresql digest to 4b17035
  mirror/postgresql/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5061 fix(images): update bitnami/solr digest to cff3d18
  mirror/solr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5059 fix(images): update bitnami/prometheus-operator digest to e6140e9
  mirror/prometheus-operator/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5062 fix(images): update bitnami/thanos digest to 8f62a31
  mirror/thanos/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5067 fix(images): update bsyed/troddit digest to 0ee30f9
  mirror/troddit/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5070 fix(images): update coderaiser/cloudcmd digest to c93932e
  mirror/cloudcommander/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5065 fix(images): update bizmodeller/mymediaforalexa digest to 815db51
  mirror/mymediaforalexa/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5066 fix(images): update blueedge/win11react digest to 7d2c046
  mirror/win11-in-react/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5068 fix(images): update cassandra digest to 515f385
  mirror/cassandra/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5069 fix(images): update ckulka/baikal digest to 003602c
  mirror/baikal/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5072 fix(images): update dbeaver/cloudbeaver digest to 4db080d
  mirror/cloudbeaver/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5073 fix(images): update diygod/rsshub digest to 33f9243
  mirror/rsshub/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5071 fix(images): update cr.hotio.dev/hotio/autoscan digest to fe1d72e
  mirror/autoscan/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5074 fix(images): update furritos/docker-btdex digest to 81b4c80
  mirror/btdex/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5076 fix(images): update ghcr.io/linuxserver/medusa digest to 34e5be5
  mirror/medusa/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5079 fix(images): update ghcr.io/linuxserver/papermerge digest to f618245
  mirror/papermerge/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5084 fix(images): update ghcr.io/linuxserver/pwndrop digest to a311387
  mirror/pwndrop/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5080 fix(images): update ghcr.io/linuxserver/photoshow digest to 29d57bb
  mirror/photoshow/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5078 fix(images): update ghcr.io/linuxserver/mysql-workbench digest to 9ff32df
  mirror/mysql-workbench/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5082 fix(images): update ghcr.io/linuxserver/piwigo digest to 0232957
  mirror/piwigo/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5081 fix(images): update ghcr.io/linuxserver/pidgin digest to 35be859
  mirror/pidgin/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5083 fix(images): update ghcr.io/linuxserver/projectsend digest to 8d48d13
  mirror/projectsend/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5077 fix(images): update ghcr.io/linuxserver/mstream digest to 28b87ad
  mirror/mstream/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5085 fix(images): update jamiephonic/rtmps-hls-server digest to be5f3dc
  mirror/rtmps-server/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5087 fix(images): update jlesage/crashplan-pro digest to 97d1a29
  mirror/crashplanpro/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5086 fix(images): update jenkins/jenkins digest to f590790
  mirror/jenkins/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5088 fix(images): update jlongster/actual-server digest to 8b0913f
  mirror/actualserver/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5091 fix(images): update linuxserver/snapdrop digest to 2039b29
  mirror/snapdrop/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5092 fix(images): update lmscommunity/logitechmediaserver digest to 26d6453
  mirror/logitechmediaserver/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5093 fix(images): update lscr.io/linuxserver/adguardhome-sync digest to a6ece3b
  mirror/adguardhome-sync/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5094 fix(images): update lscr.io/linuxserver/apprise-api digest to 3700ec0
  mirror/apprise-api/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5089 fix(images): update joomla digest to 4ef8727
  mirror/joomla/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5090 fix(images): update kizaing/kavita digest to 026c4c7
  mirror/kavita/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5098 fix(images): update mrbrax/twitchautomator digest to 322592e
  mirror/livestreamdvr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5095 fix(images): update modem7/docker-rickroll digest to ae1275a
  mirror/rickroll-fhd-game/Dockerfile
  mirror/rickroll-fhd-onclick/Dockerfile
  mirror/rickroll-fhd/Dockerfile
  mirror/rickroll-onclick/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5099 fix(images): update mrlt8/wyze-bridge digest to aecb1d5
  mirror/docker-wyze-bridge/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5096 fix(images): update monica digest to b50fcd8
  mirror/monica/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5100 fix(images): update msjpq/firefox-vnc digest to 0cd5e17
  mirror/kdeindocker/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5097 fix(images): update mpepping/cyberchef digest to 1f6182c
  mirror/cyberchef/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5103 fix(images): update nodered/node-red digest to 524316b
  mirror/nodered/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5102 fix(images): update nginxinc/nginx-unprivileged digest to a9115ed
  mirror/nginx-unprivileged/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5101 fix(images): update nginx digest to ecc0688
  mirror/nginx/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5104 fix(images): update orhunp/rustypaste digest to 0d83488
  mirror/rustypaste/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5105 fix(images): update bitnami/phpbb digest to 77b3292
  mirror/phpbb/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5106 fix(images): update bitnami/postgresql digest to 7e7ebb0
  mirror/postgresql/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5111 fix(images): update ghcr.io/k8s-at-home/bazarr digest to a668d11
  mirror/bazarr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5107 fix(images): update bitnami/redis digest to 8b1c6b5
  mirror/redis/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5110 fix(images): update ghcr.io/k8s-at-home/apache-musicindex digest to c9bd82d
  mirror/apache-musicindex/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5109 fix(images): update ghcr.io/hotio/cloudflareddns digest to 64bdf1e
  mirror/cloudflareddns/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5114 fix(images): update ghcr.io/k8s-at-home/prowlarr-develop digest to f2f83a2
  mirror/prowlarr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5108 fix(images): update bitnami/thanos digest to d20c28d
  mirror/thanos/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5112 fix(images): update ghcr.io/k8s-at-home/nzbget digest to e5571ac
  mirror/nzbget/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5113 fix(images): update ghcr.io/k8s-at-home/nzbhydra2 digest to 9175302
  mirror/nzbhydra2/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5116 fix(images): update ghcr.io/linuxserver/sickchill digest to a62138c
  mirror/sickchill/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5115 fix(images): update ghcr.io/linuxserver/rsnapshot digest to 7574654
  mirror/rsnapshot/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5119 fix(images): update ghcr.io/linuxserver/wireshark digest to 5063956
  mirror/wireshark/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5118 fix(images): update ghcr.io/linuxserver/webgrabplus digest to 330e7fc
  mirror/webgrabplus/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5117 fix(images): update ghcr.io/linuxserver/tvheadend digest to b6ef430
  mirror/tvheadend/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5120 fix(images): update ghcr.io/phantombot/phantombot digest to 934c552
  mirror/phantombot-1/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5121 fix(images): update ghcr.io/taxel/plextraktsync digest to 99ca675
  mirror/plextraktsync/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5124 fix(images): update gogs/gogs digest to 7b50653
  mirror/gogs/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5122 fix(images): update ghcr.io/techno-tim/littlelink-server digest to d3fe0c4
  mirror/littlelink-server/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5123 fix(images): update ghostfolio/ghostfolio digest to f4a0701
  mirror/ghostfolio/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5125 fix(images): update phpipam/phpipam-www digest to 9183d5c
  mirror/phpipam-www/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5129 fix(images): update quay.io/invidious/invidious digest to 38d9630
  mirror/invidious/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5126 fix(images): update postgis/postgis digest to ba26dd3
  mirror/postgis/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5127 fix(images): update promasu/cryptpad digest to 14904c6
  mirror/cryptpad/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5131 fix(images): update randomninjaatk/amtd digest to 83ad489
  mirror/amtd/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5130 fix(images): update quay.io/pussthecatorg/rimgo digest to ac1bef4
  mirror/rimgo/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5128 fix(images): update quay.io/hedgedoc/hedgedoc digest to eb6e069
  mirror/hedgedoc/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5132 fix(images): update randomninjaatk/lidarr-extended digest to 32582e1
  mirror/lidarr-extended/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5133 fix(images): update randomninjaatk/raromprocessor digest to ce00f82
  mirror/ra-rom-processor/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5134 fix(images): update randomninjaatk/sonarr-sma digest to a81fd70
  mirror/sonarr-sma/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5136 fix(images): update tombursch/kitchenowl digest to c74878f
  mirror/kitchenowl-backend/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5135 fix(images): update tiredofit/freescout digest to caad695
  mirror/freescout/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5137 fix(images): update ydkn/cups digest to 55b24df
  mirror/cups-server/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5140 feat(images): update ghost to 5.8.2
  mirror/ghost/Dockerfile
Labels: automerge, renovate/image, dep/minor

#5138 fix(images): update advplyr/audiobookshelf to 2.1.2
  mirror/audiobookshelf/Dockerfile
Labels: automerge, renovate/image, dep/patch

#5139 feat(images): update ghcr.io/k8s-at-home/plex to v1.28.0.5999-97678ded3
  mirror/plex/Dockerfile
Labels: automerge, renovate/image, dep/minor

#5141 fix(images): update bitnami/alertmanager digest to 6df9a02
  mirror/alertmanager/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5144 fix(images): update bitnami/prometheus digest to 7304048
  mirror/prometheus/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5142 fix(images): update bitnami/dokuwiki digest to 7124756
  mirror/dokuwiki/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5146 fix(images): update bitnami/solr digest to 3d68395
  mirror/solr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5145 fix(images): update bitnami/prometheus-operator digest to 7434807
  mirror/prometheus-operator/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5143 fix(images): update bitnami/mariadb digest to 3cec30a
  mirror/mariadb/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5148 fix(images): update drone/drone digest to 4efb0af
  mirror/drone/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5147 fix(images): update diygod/rsshub digest to 9cc6299
  mirror/rsshub/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5150 fix(images): update ghcr.io/k8s-at-home/readarr-develop digest to deb368d
  mirror/readarr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5149 fix(images): update ghcr.io/k8s-at-home/radarr digest to 4273dfa
  mirror/radarr/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5152 fix(images): update ghcr.io/linuxserver/remmina digest to 1d4f241
  mirror/remmina/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5151 fix(images): update ghcr.io/linuxserver/quassel-core digest to 48d33eb
  mirror/quassel-core/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5155 fix(images): update ich777/chrome digest to b03ea08
  mirror/chromium/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5153 fix(images): update goobaroo/allthemods7 digest to 8d413a6
  mirror/allthemods7/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5157 fix(images): update ich777/xonotic digest to 63a9486
  mirror/xonotic/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5159 fix(images): update jeeaaasustest/youtube-dl digest to f299df9
  mirror/youtube-dl/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5154 fix(images): update goobaroo/ftbdirewolf20_118 digest to e46f05f
  mirror/ftbdirewolf20-118/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5160 fix(images): update linuxserver/calibre-web digest to fbe3c65
  mirror/calibre-web/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5161 fix(images): update maihai/invoiceninja_v5 digest to c8a5b71
  mirror/invoiceninja-v5/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5162 fix(images): update matrixdotorg/synapse digest to 3c8dc22
  mirror/matrix-synapse/Dockerfile
Labels: automerge, renovate/image, dep/digest

#5166 fix(images): update metabase/metabase digest to 1ca5ff5
  mirror/metabase/Dockerfile
Labels: automerge, renovate/image, dep/digest
